config/routes.rb
RecipeBox::Application.routes.draw do
  resources :recipes do
    collection do
      post 'search'
      get 'search(/:q)' => 'recipes#search', :as => 'search'
      get :category_search
      get :ingredient_search
    end
  end
  root :to => 'recipes#box'
end

app/models/category.rb
class Category
  include Mongoid::Document
  include Mongoid::Search

  field :name

  search_in :name

  has_many :recipes

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/ingredient.rb
class Ingredient
  include Mongoid::Document

  field :quantity
  field :name

  embedded_in :recipe, :inverse_of => :ingredients

  validates_presence_of :name
  after_save :parse_quantity
end

app/models/recipe.rb
class Recipe
  include Mongoid::Document
  include Mongoid::Search

  field :directions
  field :name
  field :slug

  embeds_many :ingredients

  belongs_to :category

  search_in :name, :category => :name, :ingredients => :name

  validates_associated :category
  validates_presence_of :name, :directions, :slug
  validates_uniqueness_of :name, :slug

  before_validation :set_slug_from_name

  ALL_BLANK = Proc.new{ |h| h.all?{ |_, v| v.blank? } }

  accepts_nested_attributes_for :ingredients, :reject_if => ALL_BLANK,
      :allow_destroy => true

  def self.find_by_slug! slug
    where(:slug => slug).first or
      raise Mongoid::Errors::DocumentNotFound.new(self.class, :slug => slug)
  end

  def category_name
    category.try(:name)
  end

  def to_param
    self[:slug]
  end

  protected

  def set_slug_from_name
    self[:slug] = self[:name].parameterize unless self[:name].blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper :layout
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_filter :set_category_id, :only => [:update, :create]
  before_filter :load, :only => [:show, :edit, :update, :destroy]

  respond_to :html, :js

  def index
    @recipes = Recipe.order_by(:name.asc).page(params[:page]).per(10)

    respond_with @recipes
  end

  def search
    @recipes = Recipe.full_text_search(params[:q], match: :all)
    @recipes = @recipes.order_by(:name.asc).page(params[:page]).per(10)

    respond_with @recipes do |format|
      format.html { render :action => 'index' }
    end
  end

  def box
    respond_to do |format|
      format.html
    end
  end

  def show
    respond_with @recipe
  end

  def new
    @recipe = Recipe.new params[:recipe]
    respond_with @recipe
  end

  def edit
    respond_with @recipe
  end

  def create
    @recipe = Recipe.new(params[:recipe])
    @recipe.save

    respond_with @recipe
  end

  def update
    @recipe.update_attributes params[:recipe]

    respond_with @recipe
  end

  def destroy
    @recipe.destroy

    respond_with @recipe do |format|
      format.js { redirect_to :action => 'index' }
    end
  end

  def category_search
    @categories = Category.full_text_search(params[:q]).limit(params[:limit].to_i)

    render :text => @categories.map(&:name).join("\n")
  end

  protected

  def load
    @recipe = Recipe.find_by(:slug => params[:id])
  end

  def set_category_id
    name = params[:recipe].delete :category_name
    category = Category.where(:name => name).first

    if category
      params[:recipe][:category] = category
    elsif name.present?
      params[:recipe][:category] = Category.create! :name => name
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Redcarpet

  def html_options
    {:filter_html => true, :hard_wrap => true}
  end

  def markdown_options
    {:autolink => true, :no_intra_emphasis => true, :superscript => true}
  end

  def markdown text
    @markdown ||= Markdown.new(Render::HTML.new(html_options), markdown_options)
    @markdown.render(text).html_safe
  end
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= show_title? ? yield(:title) : 'Recipe Box' %></title>
    <%= stylesheet_link_tag 'application', :media => 'all' %>
    <%= javascript_include_tag 'box' %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <div id='name'>Recipes</div>

      <div id='buttons'>
        <%= link_to content_tag(:span, 'Add recipe'),
              new_recipe_path, :class => 'add' %>

        <%= link_to content_tag(:span, 'Search'),
              :recipes, :class => 'search' %>
      </div>

      <div id='card'>
        <%= link_to 'go back', root_path, :class => 'close' %>

        <div class='content'>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.js.erb
(function() { <%= yield %> })();

app/views/recipes/_form.html.erb
<%= form_for @recipe, :remote => true do |f| %>
  <%= render 'shared/error_messages', :target => @recipe %>

  <div class='col1'>
    <dl id='recipe'>
      <dt><%= f.label :name %></dt>
      <dd><%= f.text_field :name %></dd>

      <dt><%= f.label :category_name, 'Category' %></dt>
      <dd><%= f.text_field :category_name %></dd>
    </dl>

    <div>
      <%= f.label :directions %>
      <a href='http://en.wikipedia.org/wiki/Markdown' class='format'
         target='_blank'>Formatting</a>
      <br/>
      <%= f.text_area :directions %>
    </div>
  </div>
  <div class='col2' id='ingredients'>
    <h4>Ingredients <%= link_to 'add', '#', :class => 'add' %></h4>

    <dl>
      <dt>Quantity</dt>
      <dd>Name</dd>
    </dl>
    <%= f.fields_for :ingredients do |f2| %>
      <%= render 'ingredient', :f => f2 %>
    <% end %>
  </div>

  <div style='display:none' id='new-ingredient'>
    <%= f.fields_for :ingredients, @recipe.ingredients.build,
            :child_index => 'REPLACE_ME' do |f2| %>
      <%= render 'ingredient', :f => f2 %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/_ingredient.html.erb
<div class='ingredient'>
  <div class='close'>X</div>
  <%= f.text_field :quantity, :class => 'quantity' %>
  <%= f.text_field :name, :class => 'ingredient' %>
  <% unless f.object.new_record? %>
    <%= f.hidden_field :_destroy, :class => 'remove' %>
  <% end %>
</div>

app/views/recipes/_recipe.html.erb
<div class='recipe'>
  <%= link_to recipe.name, recipe %>

  <% if recipe.category.present? %>
    (<%= recipe.category.name %>)
  <% end %>
</div>

app/views/recipes/box.html.erb
<%# Nothing is here on purpose %>

app/views/recipes/create.js.erb
setContent("<%=j render(:template => @recipe.errors.any? ? 'recipes/new' :
                                       'recipes/show', :formats => [:html]) %>");

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<div id='bottom-links'>
  <%= link_to 'Show', @recipe %> |
  <%= link_to 'All Recipes', recipes_path %>
</div>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<div class='search'>
  <%= form_tag [:search, :recipes], :remote => true, :method => 'get' do %>
    <div>
      <%= text_field_tag :q, params[:q], :autocomplete => 'off',
            :placeholder => 'Search', :autofocus => true %>
    </div>
  <% end %>

  <div class='friends'>
    <%= link_to 'New Recipe', new_recipe_path %>
  </div>
</div>

<div id='results' class='pagination-container'>
  <%= render @recipes %>
  <%= paginate @recipes %>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<div id='bottom-links'>
  <%= link_to 'All Recipes', recipes_path %>
</div>

app/views/recipes/search.js.erb
setContent("<%=j render(:template => 'recipes/index', :formats => [:html]) %>");

app/views/recipes/show.html.erb
<% title @recipe.name + ' - Recipe Box' %>

<h2 class='recipe'>
  <%= @recipe.name %>
  <%= link_to '[edit]', [:edit, @recipe] %>
</h2>

<div class='scroll'>
  <ul>
    <% @recipe.ingredients.each do |ingredient| %>
      <li>
        <% if ingredient.quantity.present? %>
          <%= ingredient.quantity %> &mdash;
        <% end %>
        <%= ingredient.name %>
      </li>
    <% end %>
  </ul>

  <%= markdown @recipe.directions %>
</div>

<div id='bottom-links'>
  <%= link_to 'Remove Recipe', @recipe, :method => :delete,
        :confirm => 'Are you sure?' %> |

  <%= link_to 'Add Recipe', new_recipe_path %> |
  <%= link_to 'All Recipes', recipes_path %>
</div>

app/views/recipes/update.js.erb
<%= render :template => 'recipes/create' %>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
  <div id='errorExplanation'>
    <h2><%= pluralize(target.errors.count, 'error') %> prohibited this recipe from being saved:</h2>

    <ul>
    <% target.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_friends.html.erb
<h1>Friends Using Recipe Box</h1>

<div id='friends'>
  <ul>
    <% current_user.friends.each do |friend| %>
      <li><%= link_to friend.name, user_path(friend) %></li>
    <% end %>
  </ul>
</div>

<div id='bottom-links'>
  <%= link_to 'Your Recipes', root_path %>
</div>